# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638802b9640da2b2791df0778efa40ea7a7f3c259a8ff9b2036efd79ed3f87d1e1a2c5656064a11b5b69b718d0f1db6e7b3da174a04c643164bddaf5bb901da1

test:
  secret_key_base: d367c8f90caa60a069fa7e911abdf98e953267d7a6dd0c28a5f0db84df6facca1f24be7702fca1fb075722259d80fe452994f64b45b0b5084971539f8105096a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
